# -*- coding: utf-8 -*-
"""Bioinformatics tool V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hV0-3DCz1V2bTatV9orASoQTxUb09qS3
"""

from google.colab import files

# File read function
def read_multiple_fasta(filename):
    sequences = {}
    current_seq_id = ""

    file = open(filename, "r")

    for line in file:
        line = line.strip()

        if line.startswith(">"):
            current_seq_id = line
            sequences[current_seq_id] = ""
        else:
            sequences[current_seq_id] += line

    file.close()
    return sequences

# Analysis function
def analyze_dna(sequence):
    A = sequence.count("A")
    T = sequence.count("T")
    G = sequence.count("G")
    C = sequence.count("C")

    total = len(sequence)
    if total == 0:
        return A, T, G, C, total, 0

    gc = (G + C) / total * 100

    return A, T, G, C, total, gc

def simple_alignment(seq1, seq2):
    length = min(len(seq1), len(seq2))
    matches = 0
    mutations = []

    for i in range(length):
        if seq1[i] == seq2[i]:
            matches += 1
        else:
            mutations.append((i+1, seq1[i], seq2[i]))

    similarity = (matches / length) * 100

    return similarity, mutations

# File upload
uploaded = files.upload()
filename = next(iter(uploaded))
sequences = read_multiple_fasta(filename)

# Results
for seq_id, dna_sequence in sequences.items():
    if dna_sequence:
        A, T, G, C, total, gc = analyze_dna(dna_sequence)

        print(f" DNA Analysis Report for {seq_id}")
        print(f"Length: {total} nucleotides")
        print(f"A: {A}")
        print(f"T: {T}")
        print(f"G: {G}")
        print(f"C: {C}")
        print(f"GC Content: {round(gc, 2)}%")
    else:
        print(f"\nNo DNA sequence to analyze for {seq_id}.")

seq_list = list(sequences.values())

if len(seq_list) >= 2:
    sim, muts = simple_alignment(seq_list[0], seq_list[1])

    print("Alignment Result")
    print("Similarity:", round(sim, 2), "%")

    print("Mutations:")
    for m in muts:
        print("Position", m[0], ":", m[1], "->", m[2])