# -*- coding: utf-8 -*-
"""Bioinformatics tool V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hV0-3DCz1V2bTatV9orASoQTxUb09qS3
"""

from google.colab import files

# File read function
def read_fasta(filename):
    with open(filename, "r") as file:
        lines = file.readlines()

    sequence = ""
    for line in lines:
        if not line.startswith(">"):
            sequence += line.strip()

    return sequence

# Analysis function
def analyze_dna(sequence):
    A = sequence.count("A")
    T = sequence.count("T")
    G = sequence.count("G")
    C = sequence.count("C")

    total = len(sequence)
    if total == 0:
        return A, T, G, C, total, 0

    gc = (G + C) / total * 100

    return A, T, G, C, total, gc

# File upload
uploaded = files.upload()
filename = next(iter(uploaded))
sequence = read_fasta(filename)
if sequence:
    A, T, G, C, total, gc = analyze_dna(sequence)

    print("DNA Analysis Report")
    print(f"Length: {total} nucleotides")
    print(f"A: {A}")
    print(f"T: {T}")
    print(f"G: {G}")
    print(f"C: {C}")
    print(f"GC Content: {round(gc, 2)}%")
else:
    print("No DNA sequence to analyze.")